defaults:
  - model: hifigan
  - metrics: synthesize
  - datasets: customdirdataset2 # we do not want to run inference on training data
  - dataloader: example
  - transforms: example
  - _self_
synthesizer:
  device_tensors: ['signal_gt'] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: null
skip_model_load: False
