defaults:
  - model: synthesizer
  - writer: wandb
  - metrics: synthesize
  - datasets: ljspeech
  - dataloader: example
  - transforms: example
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  betas: [0.8, 0.99]
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 1
  gamma: 0.999
trainer:
  skip_oom: false
  log_step: 100
  n_epochs: 100
  epoch_len: 200
  eval_len: null
  max_grad_norm: 200
  device_tensors: ["signal_gt"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min train_MSE" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  from_pretrained: null # path to the pretrained model
  seed: 1
